config/routes.rb
Sensormanager::Application.routes.draw do
  resources :medidas

  resources :sensors do
    member do
      get 'medidas'
    end
  end

  resources :concentradors do
    member do 
      get 'sensores'
    end
  end
  

  resources :categoria_equipos do
    member do
      get 'estaciones'
    end
  end

  get 'topmedidas' => 'welcome#topmedidas'

  root :to => 'welcome#index'

  

end

app/models/concentrador.rb
class Concentrador < ActiveRecord::Base
  belongs_to :categoria_equipo
  has_many :sensors
  has_many :medidas, :through => :sensors
  
  validates :categoria_equipo, :nombre, :estado, presence: { message: " Obligatorio"}
  validates :nombre, uniqueness: {message: " debe ser unico"}
  validates :gis_latitud, :gis_longitud, numericality: true
end

app/controllers/concentradors_controller.rb
class ConcentradorsController < ApplicationController
  before_action :set_concentrador, only: [:show, :edit, :update, :destroy, :sensores]

  # GET /concentradors
  # GET /concentradors.json
  def index
    @concentradors = Concentrador.all
  end

  # GET /concentradors/1
  # GET /concentradors/1.json
  def show
  end

  def sensores
  end
  
  # GET /concentradors/new
  def new
    @concentrador = Concentrador.new
  end

  # GET /concentradors/1/edit
  def edit
  end

  # POST /concentradors
  # POST /concentradors.json
  def create
    @concentrador = Concentrador.new(concentrador_params)

    respond_to do |format|
      if @concentrador.save
        format.html { redirect_to @concentrador, notice: 'Concentrador was successfully created.' }
        format.json { render action: 'show', status: :created, location: @concentrador }
      else
        format.html { render action: 'new' }
        format.json { render json: @concentrador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concentradors/1
  # PATCH/PUT /concentradors/1.json
  def update
    respond_to do |format|
      if @concentrador.update(concentrador_params)
        format.html { redirect_to @concentrador, notice: 'Concentrador was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @concentrador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concentradors/1
  # DELETE /concentradors/1.json
  def destroy
    @concentrador.destroy
    respond_to do |format|
      format.html { redirect_to concentradors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concentrador
      @concentrador = Concentrador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concentrador_params
      params.require(:concentrador).permit(:categoria_equipo_id, :nombre, :descripcion, :estado, :gis_latitud, :gis_longitud, :mac_address, :numero_serie, :ip_address, :ip_port)
    end
end

app/helpers/concentradors_helper.rb
module ConcentradorsHelper
end

app/views/concentradors/_form.html.erb
<%= semantic_form_for @concentrador do |f| %>
  <%= f.inputs do %>
    <%= f.input :categoria_equipo, :as => :select, :member_label => :nombre%>
    <%= f.input :nombre %>
    <%= f.input :descripcion %>
    <%= f.input :estado %>
    <%= f.input :gis_latitud %>
    <%= f.input :gis_longitud %>
    <%= f.input :mac_address %>
    <%= f.input :numero_serie %>
    <%= f.input :ip_address %>
    <%= f.input :ip_port %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/concentradors/edit.html.erb
<h1>Editar concentrador</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @concentrador %> |
<%= link_to 'Volver', concentradors_path %>

app/views/concentradors/index.html.erb
<h1>Listado de concentradores</h1>

<table>
  <thead>
    <tr>
      <th>Categoria equipo</th>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Estado</th>
      <th>Gis latitud</th>
      <th>Gis longitud</th>
      <th>Mac address</th>
      <th>Numero serie</th>
      <th>Ip address</th>
      <th>Ip port</th>
      <th>N. Sensores</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @concentradors.each do |concentrador| %>
      <tr>
        <td><%= concentrador.categoria_equipo.nombre %></td>
        <td><%= concentrador.nombre %></td>
        <td><%= concentrador.descripcion %></td>
        <td><%= concentrador.estado %></td>
        <td><%= concentrador.gis_latitud %></td>
        <td><%= concentrador.gis_longitud %></td>
        <td><%= concentrador.mac_address %></td>
        <td><%= concentrador.numero_serie %></td>
        <td><%= concentrador.ip_address %></td>
        <td><%= concentrador.ip_port %></td>
        <td><%= concentrador.sensors.count %></td>
        <td><%= link_to 'Mostrar', concentrador %></td>
        <td><%= link_to 'Editar', edit_concentrador_path(concentrador) %></td>
        <td><%= link_to 'Eliminar', concentrador, method: :delete, data: { confirm: 'Estas seguro que quieres eliminarlo?' } %></td>
        <td><%= link_to 'Sensores', sensores_concentrador_path(concentrador) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Concentrador', new_concentrador_path %>

app/views/concentradors/new.html.erb
<h1>Nuevo concentrador</h1>

<%= render 'form' %>

<%= link_to 'Back', concentradors_path %>

app/views/concentradors/sensores.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @concentrador.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @concentrador.descripcion %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @concentrador.estado %>
</p>

<p>
  <strong>Gis latitud:</strong>
  <%= @concentrador.gis_latitud %>
</p>

<p>
  <strong>Gis longitud:</strong>
  <%= @concentrador.gis_longitud %>
</p>

<p>
  <strong>Mac address:</strong>
  <%= @concentrador.mac_address %>
</p>

<p>
  <strong>Numero serie:</strong>
  <%= @concentrador.numero_serie %>
</p>

<p>
  <strong>Ip address:</strong>
  <%= @concentrador.ip_address %>
</p>

<p>
  <strong>Ip port:</strong>
  <%= @concentrador.ip_port %>
</p>

<h1>Sensores</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Estado</th>
      <th>Parametro</th>
      <th>Valor</th>
      <th>Uds</th>
    </tr>
  </thead>

  <tbody>
    <% @concentrador.sensors.each do |sensor| %>
      <tr>
        <td><%= sensor.nombre %></td>
        <td><%= sensor.descripcion %></td>
        <td><%= sensor.estado %></td>
        <td><%= sensor.parametro %></td>
        <td><%= sensor.valor %></td>
        <td><%= sensor.uds %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Editar', edit_concentrador_path(@concentrador) %> |
<%= link_to 'Volver', concentradors_path %>

app/views/concentradors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Categoria equipo:</strong>
  <%= @concentrador.categoria_equipo.nombre %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @concentrador.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @concentrador.descripcion %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @concentrador.estado %>
</p>

<p>
  <strong>Gis latitud:</strong>
  <%= @concentrador.gis_latitud %>
</p>

<p>
  <strong>Gis longitud:</strong>
  <%= @concentrador.gis_longitud %>
</p>

<p>
  <strong>Mac address:</strong>
  <%= @concentrador.mac_address %>
</p>

<p>
  <strong>Numero serie:</strong>
  <%= @concentrador.numero_serie %>
</p>

<p>
  <strong>Ip address:</strong>
  <%= @concentrador.ip_address %>
</p>

<p>
  <strong>Ip port:</strong>
  <%= @concentrador.ip_port %>
</p>

<%= link_to 'Editar', edit_concentrador_path(@concentrador) %> |
<%= link_to 'Volver', concentradors_path %>