config/routes.rb
Sensormanager::Application.routes.draw do
  resources :medidas

  resources :sensors do
    member do
      get 'medidas'
    end
  end

  resources :concentradors do
    member do 
      get 'sensores'
    end
  end
  

  resources :categoria_equipos do
    member do
      get 'estaciones'
    end
  end

  get 'topmedidas' => 'welcome#topmedidas'

  root :to => 'welcome#index'

  

end

app/models/categoria_equipo.rb
class CategoriaEquipo < ActiveRecord::Base
  has_many :concentradors
  has_many :sensors, :through => :concentradors
  has_many :medidas, :through => :sensors

  validates :nombre, presence: { message: " Obligatorio"}, uniqueness: {message: " debe ser unico"}
end

app/controllers/categoria_equipos_controller.rb
class CategoriaEquiposController < ApplicationController
  before_action :set_categoria_equipo, only: [:show, :edit, :update, :destroy, :estaciones]

  # GET /categoria_equipos
  # GET /categoria_equipos.json
  def index
    @categoria_equipos = CategoriaEquipo.all
  end

  # GET /categoria_equipos/1
  # GET /categoria_equipos/1.json
  def show
  end

  def estaciones
  end

  # GET /categoria_equipos/new
  def new
    @categoria_equipo = CategoriaEquipo.new
  end

  # GET /categoria_equipos/1/edit
  def edit
  end

  # POST /categoria_equipos
  # POST /categoria_equipos.json
  def create
    @categoria_equipo = CategoriaEquipo.new(categoria_equipo_params)

    respond_to do |format|
      if @categoria_equipo.save
        format.html { redirect_to @categoria_equipo, notice: 'Categoria equipo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @categoria_equipo }
      else
        format.html { render action: 'new' }
        format.json { render json: @categoria_equipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categoria_equipos/1
  # PATCH/PUT /categoria_equipos/1.json
  def update
    respond_to do |format|
      if @categoria_equipo.update(categoria_equipo_params)
        format.html { redirect_to @categoria_equipo, notice: 'Categoria equipo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @categoria_equipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoria_equipos/1
  # DELETE /categoria_equipos/1.json
  def destroy
    @categoria_equipo.destroy
    respond_to do |format|
      format.html { redirect_to categoria_equipos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categoria_equipo
      @categoria_equipo = CategoriaEquipo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categoria_equipo_params
      params.require(:categoria_equipo).permit(:nombre, :descripcion)
    end
end

app/helpers/categoria_equipos_helper.rb
module CategoriaEquiposHelper
end

app/views/categoria_equipos/_form.html.erb
<%= form_for(@categoria_equipo) do |f| %>
  <% if @categoria_equipo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categoria_equipo.errors.count, "error") %> prohibited this categoria_equipo from being saved:</h2>

      <ul>
      <% @categoria_equipo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categoria_equipos/edit.html.erb
<h1>Editing categoria_equipo</h1>

<%= render 'form' %>

<%= link_to 'Show', @categoria_equipo %> |
<%= link_to 'Back', categoria_equipos_path %>

app/views/categoria_equipos/estaciones.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @categoria_equipo.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @categoria_equipo.descripcion %>
</p>

<h1>
  Estaciones
</h1>
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Estado</th>
      <th>Gis latitud</th>
      <th>Gis longitud</th>
      <th>Mac address</th>
      <th>Numero serie</th>
      <th>Ip address</th>
      <th>Ip port</th>
    </tr>
  </thead>

  <tbody>
    <% @categoria_equipo.concentradors.each do |concentrador| %>
      <tr>
        <td><%= concentrador.nombre %></td>
        <td><%= concentrador.descripcion %></td>
        <td><%= concentrador.estado %></td>
        <td><%= concentrador.gis_latitud %></td>
        <td><%= concentrador.gis_longitud %></td>
        <td><%= concentrador.mac_address %></td>
        <td><%= concentrador.numero_serie %></td>
        <td><%= concentrador.ip_address %></td>
        <td><%= concentrador.ip_port %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_categoria_equipo_path(@categoria_equipo) %> |
<%= link_to 'Back', categoria_equipos_path %>

app/views/categoria_equipos/index.html.erb
<h1>Categorias de estaciones metereologicas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>N. Estaciones</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categoria_equipos.each do |categoria_equipo| %>
      <tr>
        <td><%= categoria_equipo.nombre %></td>
        <td><%= categoria_equipo.descripcion %></td>
        <td><%= categoria_equipo.concentradors.count %></td>
        <td><%= link_to 'Show', categoria_equipo %></td>
        <td><%= link_to 'Edit', edit_categoria_equipo_path(categoria_equipo) %></td>
        <td><%= link_to 'Destroy', categoria_equipo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Estaciones', estaciones_categoria_equipo_path(categoria_equipo) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Categoria equipo', new_categoria_equipo_path %>

app/views/categoria_equipos/new.html.erb
<h1>New categoria_equipo</h1>

<%= render 'form' %>

<%= link_to 'Back', categoria_equipos_path %>

app/views/categoria_equipos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @categoria_equipo.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @categoria_equipo.descripcion %>
</p>

<%= link_to 'Edit', edit_categoria_equipo_path(@categoria_equipo) %> |
<%= link_to 'Back', categoria_equipos_path %>