config/routes.rb
Sensormanager::Application.routes.draw do
  resources :medidas

  resources :sensors do
    member do
      get 'medidas'
    end
  end

  resources :concentradors do
    member do 
      get 'sensores'
    end
  end
  

  resources :categoria_equipos do
    member do
      get 'estaciones'
    end
  end

  get 'topmedidas' => 'welcome#topmedidas'

  root :to => 'welcome#index'

  

end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
  belongs_to :concentrador
  has_many :medidas
  
  validates :concentrador, :nombre, :estado, :parametro, :valor, presence: { message: "Campo Obligatorio"}
  validates :valor, numericality: true
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :set_sensor, only: [:show, :edit, :update, :destroy, :medidas]

  # GET /sensors
  # GET /sensors.json
  def index
    @sensors = Sensor.all
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
  end

  def medidas
  end

  # GET /sensors/new
  def new
    @sensor = Sensor.new
  end

  # GET /sensors/1/edit
  def edit
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(sensor_params)

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to @sensor, notice: 'Sensor creado de forma satistactoria.' }
        format.json { render action: 'show', status: :created, location: @sensor }
      else
        format.html { render action: 'new' }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensors/1
  # PATCH/PUT /sensors/1.json
  def update
    respond_to do |format|
      if @sensor.update(sensor_params)
        format.html { redirect_to @sensor, notice: 'Sensor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor.destroy
    respond_to do |format|
      format.html { redirect_to sensors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor
      @sensor = Sensor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensor_params
      params.require(:sensor).permit(:concentrador_id, :nombre, :descripcion, :estado, :parametro, :valor, :uds)
    end
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/sensors/_form.html.erb
<%= semantic_form_for @sensor do |f| %>
  <%= f.inputs do %>
    <%= f.input :concentrador, :as => :select, :member_label => :nombre %>
    <%= f.input :nombre %>
    <%= f.input :descripcion %>
    <%= f.input :estado %>
    <%= f.input :parametro %>
    <%= f.input :valor %>
    <%= f.input :uds %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/sensors/edit.html.erb
<h1>Editing sensor</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @sensor %> |
<%= link_to 'Volver', sensors_path %>

app/views/sensors/index.html.erb
<h1>Listado de sensores</h1>

<table>
  <thead>
    <tr>
      <th>Concentrador</th>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Estado</th>
      <th>Parametro</th>
      <th>Valor</th>
      <th>Uds</th>
      <th>N. Medidas</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sensors.each do |sensor| %>
      <tr>
        <td><%= sensor.concentrador.nombre %></td>
        <td><%= sensor.nombre %></td>
        <td><%= sensor.descripcion %></td>
        <td><%= sensor.estado %></td>
        <td><%= sensor.parametro %></td>
        <td><%= sensor.valor %></td>
        <td><%= sensor.uds %></td>
        <td><%= sensor.medidas.count%></td>
        <td><%= link_to 'Mostrar', sensor %></td>
        <td><%= link_to 'Editar', edit_sensor_path(sensor) %></td>
        <td><%= link_to 'Eliminar', sensor, method: :delete, data: { confirm: 'Esta seguro que desea eliminarlo?' } %></td>
        <td><%= link_to 'Medidas', medidas_sensor_path(sensor) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Sensor', new_sensor_path %>

app/views/sensors/medidas.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @sensor.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @sensor.descripcion %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @sensor.estado %>
</p>

<p>
  <strong>Parametro:</strong>
  <%= @sensor.parametro %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @sensor.valor %>
</p>

<p>
  <strong>Uds:</strong>
  <%= @sensor.uds %>
</p>

<h1>Medidas</h1>

<table>
  <thead>
    <tr>
      <th>Sensor</th>
      <th>Fecha</th>
      <th>Valor</th>
    </tr>
  </thead>

  <tbody>
    <% @sensor.medidas.each do |medida| %>
      <tr>
        <td><%= medida.sensor.nombre %></td>
        <td><%= medida.fecha %></td>
        <td><%= medida.valor %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sensors/new.html.erb
<h1>Nuevo sensor</h1>

<%= render 'form' %>

<%= link_to 'Volver', sensors_path %>

app/views/sensors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Concentrador:</strong>
  <%= @sensor.concentrador.nombre %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @sensor.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @sensor.descripcion %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @sensor.estado %>
</p>

<p>
  <strong>Parametro:</strong>
  <%= @sensor.parametro %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @sensor.valor %>
</p>

<p>
  <strong>Uds:</strong>
  <%= @sensor.uds %>
</p>

<%= link_to 'Editar', edit_sensor_path(@sensor) %> |
<%= link_to 'Volver', sensors_path %>