config/routes.rb
Sensormanager::Application.routes.draw do
  resources :medidas

  resources :sensors do
    member do
      get 'medidas'
    end
  end

  resources :concentradors do
    member do 
      get 'sensores'
    end
  end
  

  resources :categoria_equipos do
    member do
      get 'estaciones'
    end
  end

  get 'topmedidas' => 'welcome#topmedidas'

  root :to => 'welcome#index'

  

end

app/models/medida.rb
class Medida < ActiveRecord::Base
  belongs_to :sensor

  validates :sensor, :fecha, presence: { message: "Campo Obligatorio"}
  validates :valor, numericality: true
end

app/controllers/medidas_controller.rb
class MedidasController < ApplicationController
  before_action :set_medida, only: [:show, :edit, :update, :destroy]

  # GET /medidas
  # GET /medidas.json
  def index
    @medidas = Medida.all
  end

  # GET /medidas/1
  # GET /medidas/1.json
  def show
  end

  # GET /medidas/new
  def new
    @medida = Medida.new
  end

  # GET /medidas/1/edit
  def edit
  end

  # POST /medidas
  # POST /medidas.json
  def create
    @medida = Medida.new(medida_params)

    respond_to do |format|
      if @medida.save
        format.html { redirect_to @medida, notice: 'Medida was successfully created.' }
        format.json { render action: 'show', status: :created, location: @medida }
      else
        format.html { render action: 'new' }
        format.json { render json: @medida.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medidas/1
  # PATCH/PUT /medidas/1.json
  def update
    respond_to do |format|
      if @medida.update(medida_params)
        format.html { redirect_to @medida, notice: 'Medida was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @medida.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medidas/1
  # DELETE /medidas/1.json
  def destroy
    @medida.destroy
    respond_to do |format|
      format.html { redirect_to medidas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medida
      @medida = Medida.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medida_params
      params.require(:medida).permit(:sensor_id, :fecha, :valor)
    end
end

app/helpers/medidas_helper.rb
module MedidasHelper
end

app/views/medidas/_form.html.erb
<%= semantic_form_for @medida do |f| %>
  <%= f.inputs do %>
    <%= f.input :sensor,:as => :select, :member_label => :nombre %>
    <%= f.input :fecha %>
    <%= f.input :valor %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/medidas/edit.html.erb
<h1>Editing medida</h1>

<%= render 'form' %>

<%= link_to 'Show', @medida %> |
<%= link_to 'Back', medidas_path %>

app/views/medidas/index.html.erb
<h1>Listing medidas</h1>

<table>
  <thead>
    <tr>
      <th>Sensor</th>
      <th>Fecha</th>
      <th>Valor</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @medidas.each do |medida| %>
      <tr>
        <td><%= medida.sensor.nombre %></td>
        <td><%= medida.fecha %></td>
        <td><%= medida.valor %></td>
        <td><%= link_to 'Show', medida %></td>
        <td><%= link_to 'Edit', edit_medida_path(medida) %></td>
        <td><%= link_to 'Destroy', medida, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medida', new_medida_path %>

app/views/medidas/new.html.erb
<h1>New medida</h1>

<%= render 'form' %>

<%= link_to 'Back', medidas_path %>

app/views/medidas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sensor:</strong>
  <%= @medida.sensor.nombre %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @medida.fecha %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @medida.valor %>
</p>

<%= link_to 'Edit', edit_medida_path(@medida) %> |
<%= link_to 'Back', medidas_path %>